### ISSUE TITLE
que rica demonio!

### ISSUE THREAD

**Issue by juanbraga** [mtailanian/AudioDSP#1]
:)

**Comment by mtailanian** [comment]
Jajajaj me abriste un issue ahi

me encantan estos estos medios de comunicación posmo! :P
en q andas bo?

**Comment by juanbraga** [comment]
te abrí un issue para que lo cierres cuando quieras!

**Comment by mtailanian** [comment]
jaja tas en cualquiera salchicha

**Comment by MartinRandallC** [comment]
hola.

**Comment by mtailanian** [comment]
jajaja ta pa esta la gente

**Comment by MartinRandallC** [comment]
estamos en un curso de vagonbar

**Comment by juanbraga** [comment]
‪#‎SiHayRecorteHayLucha‬
